module.exports = {
  plugins: {
    autoprefixer: {},
    '@fullhuman/postcss-purgecss': {
      content: [
        './pages/**/*.{js,ts,jsx,tsx}',
        './components/**/*.{js,ts,jsx,tsx}',
      ],
      safelist: {
        standard: [
          /^btn/,
          /^modal/,
          /^navbar/,
          /^show$/,
          /^container$/,
          /^col$/,
          /^nav$/,
          /^accordion$/,
          /^tab$/,
          /^d-/,
          /^flex-/,
          /^align-/,
          /^justify-/,
          /^text-/,
          /^bg-/,
          /^border/,
          /^rounded/,
          /^shadow/,
          /^p-/,
          /^m-/,
          /^ps-/,
          /^pe-/,
          /^py-/,
          /^px-/,
          /^ms-/,
          /^me-/,
          /^my-/,
          /^mx-/,
          /^fw-/,
          /^small$/,
          /^table/,
          /^card/,
          /^form/,
          /^badge/,
        ],
        deep: [],
        greedy: [/^container/, /^row/, /^col/, /^swiper/, /^slick/, /^img/, /^nav-item/, /^accordion/, /^tab-pane/, /^nav-link/, /^active/, /^nav-pills/],
      },
    },
  },
};
