/**
 * Paths that return 301/302 in middleware.ts (source URLs only).
 * Sitemap must not list these — Semrush flags them as "wrong" (redirect in sitemap).
 *
 * Keep in sync when adding blog (or other) redirects in middleware.ts.
 * DB-driven rules still come from url-redirections/public (see sitemapRedirectExclude.js).
 */
export const MIDDLEWARE_STATIC_SITEMAP_EXCLUDES = [
    '/blog/why-small-businesses-are-',
    '/blog/framework-for-mobile-app-development-2021-2022',
    '/blog/top-9-benefits-of-custom-mobile-application-development',
    '/blog/tips-of-choosing-software-development-company-for-startup-business',
    '/blog/best-prototyping-tools',
    '/blog/game-changer-app-development-company-clutch',
    '/blog/fintech-app-development-company-an-ultimate-guide',
    '/blog/leading-fintech-app-development-company-in-usa',
    '/blog/fintech-software-development-an-ultimate-guide',
    '/blog/llm-development-company-ultimate-guide-for-businesses',
    '/blog/streamline-court-room-with-legal-software-development-services',
    '/blog/maximize-roi-with-best-mobile-app-development-company-in-USA',
    '/blog/how-to-choose-a-mobile-app-development-company',
    '/blog/how-to-choose-a-mobile-app-development-company-for-startups',
    '/blog/how-to-choose-a-right-mobile-app-development-company',
    '/blog/how-to-choose-the-best-UI-UX-design-services-provider',
    '/blog/the-ultimate-checklist-for-choosing-the-right-ui-ux-design-company',
    '/blog/ui-ux-design-and-development-services-in-usa',
    '/blog/a-comprehensive-guide-to-custom-software-development',
    '/blog/generative-ai-app-development-guide',
    '/blog/ai-ml-development-company-in-usa-transform-your-business',
    '/blog/key-considerations-before-choosing-an-ai-ml-development-company',
    '/blog/top-10-custom-software-development-companies-in-usa-2025',
    '/blog/ai-app-development-company-a-ultimate-guide-in-2025',
    '/blog/how-long-does-it-take-time-to-develop-mobile-apps-in-2025',
    '/blog/best-tech-stack-for-ai-ml-development-2025',
    '/blog/custom-software-development-really-cost-in-2025',
    '/blog/how-much-does-cross-platform-app-development-cost-2025',
    '/blog/upcoming-web-design-trends-in-2025',
    '/blog/top-features-to-look-for-legal-software-development-services-2025',
    '/blog/top-cross-platform-frameworks-you-should-know-in-2025',
    '/blog/how-much-does-transportation-app-development-cost-in-2025',
    '/blog/why-ui-ux-design-is-critical-to-your-apps-success-in-2025',
    '/blog/how-to-find-the-best-cross-platform-app-development-company',
    '/blog/top-cross-platform-app-development-framework',
    '/blog/a-comprehensive-guide-to-cross-platform-app-development',
    '/blog/cross-platform-mobile-app-development-services',
    '/blog/how-to-Develop-a-Transportation-App-in-2025',
    '/blog/choose-right-ai-ml-development-company-for-your-business',
    '/blog/enterprise-mobile-app-development-a-complete-guide',
    '/blog/mobile-enterprise-app-development-guide',
    '/blog/the-rise-of-ai-will-be-consequential-for-blue-collar-workers',
    '/blog/how-mobile-apps-are-changing-the-way-of-doing-business',
    '/blog/how-to-develop-a-complete-bug-free-mobile-application',
    '/blog/link',
];
