export const TYPE = {
  GET_BLOG_LIST: 'API/GET_BLOG_LIST/GET_SHOWCASES',
  GET_BLOG_LIST_COUNT: 'API/GET_BLOG_LIST_COUNT/GET_SHOWCASES',
  GET_RECENT_BLOG_LIST: 'API/GET_RECENT_BLOG_LIST/GET_SHOWCASES',
  GET_BLOG_CATEGORIES: 'API/GET_BLOG_CATEGORIES/GET_SHOWCASES',
  GET_BLOG_SEARCH: 'API/GET_BLOG_SEARCH/GET_SHOWCASES',
  GET_BLOG_BY_CATEGORY: 'API/GET_BLOG_BY_CATEGORY/GET_SHOWCASES',
  GET_BLOG_ARCHIVES: 'API/GET_BLOG_ARCHIVES/GET_SHOWCASES',
  GET_BLOG_BY_ARCHIVES: 'API/GET_BLOG_BY_ARCHIVES/GET_SHOWCASES',
  GET_ALL_BLOG_BY_ARCHIVES: 'API/GET_ALL_BLOG_BY_ARCHIVES/GET_SHOWCASES',
  GET_BLOG_BY_SLUG: 'API/GET_BLOG_BY_SLUG/GET_SHOWCASES',

  GET_PORTFOLIO_LIST: 'API/GET_PORTFOLIO_LIST/GET_SHOWCASES',
  GET_PORTFOLIO_BY_ID: 'API/GET_PORTFOLIO_BY_ID/GET_SHOWCASES',
  GET_COUNTRY_LIST_PAGE: 'API/GET_COUNTRY_LIST_PAGE/GET_SHOWCASES',

  GET_PRESS_LIST: 'API/GET_PRESS_LIST/GET_SHOWCASES',
};
